resolver: lts-18.18

packages:
- .

extra-deps:
- Yampa-0.13.7
- git: https://github.com/isovector/ldtk-types.git
  commit: 0be47b237f36e4a16c6fac5d384adc733ed07711
- git: https://github.com/gbrsales/cabal-appimage.git
  commit: 0f0cf1d14d0e00abd089be0b63213bb505fb1499

